In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# 회귀분석
from statsmodels.formula.api import ols
# qqplot, 회귀분석의 상수항 추가
from statsmodels.api import qqplot, add_constant
# 선형 모델 formula(y ~ X1 + X2 + ...)
import statsmodels.formula.api as smf
# 다중공선성 확인
from statsmodels.stats.outliers_influence import variance_inflation_factor
# 선형회귀모형
from sklearn.linear_model import LinearRegression
# 변수 선택법(후진제거법)
from sklearn.feature_selection import RFE
# Scale 변환->표준화 회귀계수 산출
from sklearn.preprocessing import StandardScaler
# 평가함수
from statsmodels.tools.eval_measures import rmse
import matplotlib
# 패키지 불러오기
from sklearn.linear_model import Ridge, Lasso, ElasticNet
#from sklearn.tree import export_graphviz  환경 설정하기 어려움
#import graphviz

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
# 나무 구조 시각화  
from sklearn.tree import plot_tree
# 예측 / 회귀 random forest
from sklearn.ensemble import RandomForestRegressor
matplotlib.rc('font', family = 'Malgun Gothic') 
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import scale, minmax_scale, robust_scale

#평가 함수
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
# 음수 표시
matplotlib.rc('axes', unicode_minus=False)
matplotlib.rc('font', family = 'Malgun Gothic') 

from scipy.stats import chi2_contingency
from scipy import stats

# 로지스틱 회귀
from statsmodels.api import Logit
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

In [168]:
df = pd.read_csv("C:/Users/USER/Desktop/반도체 공정/데이터/Ion_Implantation.CSV")
df

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
0,0,NOLSM325131325,1,Implantation,1.500198e+16,1.316363e+17,6.468338e+17,3.011187e+17,6.000012e+17,30795.934,103.433,854.0,154,13,28,01-03-2019
1,1,NOLSM326132326,2,Implantation,1.105654e+16,4.367509e+16,1.041399e+18,3.026639e+17,6.000008e+17,32135.618,105.552,895.0,156,13,29,01-03-2019
2,2,NOLSM327133327,3,Implantation,1.044283e+16,1.507393e+16,6.473188e+17,2.983347e+17,5.999989e+17,31057.895,102.598,898.0,152,13,30,01-03-2019
3,3,NOLSM328134328,1,Implantation,8.885135e+15,1.022922e+17,3.408444e+17,2.999225e+17,5.999997e+17,32140.566,102.963,879.0,155,13,31,01-03-2019
4,4,NOLSM329135329,2,Implantation,1.665762e+16,7.883038e+16,7.255226e+17,3.018136e+17,6.000004e+17,31986.009,101.419,882.0,155,13,32,01-03-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,1699,NOLSM8483211,3,Implantation,1.054583e+16,9.513525e+16,6.272553e+17,3.009325e+17,6.000003e+17,32248.621,101.503,868.0,152,32,11,28-02-2019
1700,1700,NOLSM8493212,3,Implantation,6.909171e+15,5.426149e+16,1.865029e+17,3.006733e+17,6.000003e+17,32241.426,101.061,867.0,152,32,12,28-02-2019
1701,1701,NOLSM8503213,2,Implantation,9.324972e+15,7.673877e+15,3.069885e+17,2.990013e+17,5.999991e+17,32245.574,101.506,868.0,152,32,13,28-02-2019
1702,1702,NOLSM8513214,1,Implantation,1.184106e+16,2.793792e+16,3.275209e+14,2.992776e+17,6.000012e+17,32259.412,101.360,868.0,152,32,14,28-02-2019
1703,1703,NOLSM8523215,1,Implantation,1.511777e+16,1.496121e+17,7.045878e+17,2.990793e+17,6.000008e+17,32258.401,101.439,868.0,152,32,15,28-02-2019

In [48]:
df.describe()

,Unnamed: 0,Chamber_Num,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num
count,1704.000000,1704.000000,1.704000e+03,1.701000e+03,1.702000e+03,1.703000e+03,1.704000e+03,1704.000000,1704.000000,1702.000000,1704.000000,1704.000000,1704.000000
mean,851.500000,1.983568,1.180285e+16,8.003251e+16,4.463241e+17,3.002009e+17,5.999997e+17,32007.862815,103.161261,901.128085,154.696009,16.281690,27.394366
std,492.046746,0.823731,4.624857e+15,5.413832e+16,3.317184e+17,1.143206e+15,1.076270e+12,588.149740,1.654344,18.482368,2.419403,9.114164,15.586611
min,0.000000,1.000000,1.967326e+15,3.846247e+09,-6.930960e+16,2.963401e+17,5.999965e+17,29604.262000,97.744000,854.000000,148.000000,1.000000,1.000000
25%,425.750000,1.000000,8.443158e+15,3.050382e+16,1.230017e+17,2.994308e+17,5.999990e+17,31640.161000,102.063500,890.000000,153.000000,8.000000,14.000000
50%,851.500000,2.000000,1.175328e+16,8.132774e+16,4.535872e+17,3.001889e+17,5.999997e+17,32200.488500,103.295500,904.000000,155.000000,16.000000,27.500000
75%,1277.250000,3.000000,1.514341e+16,1.208584e+17,6.774005e+17,3.009382e+17,6.000004e+17,32420.668750,104.322000,915.000000,156.000000,24.000000,41.000000
max,1703.000000,3.000000,2.403938e+16,2.720974e+17,1.401808e+18,3.036145e+17,6.000025e+17,33675.551000,107.376000,944.000000,162.000000,32.000000,54.000000

In [5]:
df.isnull().sum()

Unnamed: 0           0
No_Die               0
Chamber_Num          0
process4             0
Flux60s              3
Flux90s              3
Flux160s             2
Flux480s             1
Flux840s             1
input_Energy         0
Temp_implantation    0
Furance_Temp         2
RTA_Temp             0
Lot_Num              0
Wafer_Num            0
Datetime             0
dtype: int64

In [51]:
df.loc[df.isnull()['Flux60s']]   #

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
1107,1107,NOLSM703271703,1,Implantation,NaN,NaN,NaN,3.002952e+17,5.999998e+17,32437.886,104.475,NaN,157,27,28,23-02-2019
1161,1161,NOLSM703271,2,Implantation,NaN,NaN,NaN,3.002952e+17,5.999998e+17,32437.886,104.475,NaN,157,27,1,23-02-2019
1239,1239,NOLSM7542825754,1,Implantation,NaN,4.623857e+12,7.243678e+11,3.006356e+17,6.000000e+17,32463.404,103.309,881.0,155,28,52,24-02-2019

In [52]:
df.loc[df.isnull()['Flux90s']] #

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
1107,1107,NOLSM703271703,1,Implantation,NaN,NaN,NaN,3.002952e+17,5.999998e+17,32437.886,104.475,NaN,157,27,28,23-02-2019
1161,1161,NOLSM703271,2,Implantation,NaN,NaN,NaN,3.002952e+17,5.999998e+17,32437.886,104.475,NaN,157,27,1,23-02-2019
1323,1323,NOLSM757291757,1,Implantation,1.929673e+16,NaN,3.089572e+17,2.990970e+17,6.000016e+17,32444.191,101.359,877.0,152,29,28,25-02-2019

In [53]:
df.loc[df.isnull()['Flux480s']] #

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
1229,1229,NOLSM7442815744,3,Implantation,1.782448e+16,1.228572e+16,1.498824e+17,NaN,5.999995e+17,32446.311,103.461,884.0,155,28,42,24-02-2019

In [54]:
df.loc[df.isnull()['Flux840s']]

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
1237,1237,NOLSM7522823752,2,Implantation,4.243255e+15,5.797774e+16,2.256413e+10,3.014716e+17,NaN,32449.708,101.118,882.0,152,28,50,24-02-2019

In [ ]:
결측치 총 6행

## 60 결측치 평균으로 채움

In [169]:
df['Flux60s'].fillna(df['Flux60s'].agg('mean'), inplace = True)

In [86]:
df.loc[1107]

Unnamed: 0                           1107
No_Die                     NOLSM703271703
Chamber_Num                             1
process4                     Implantation
Flux60s               11802845338036440.0
Flux90s                               NaN
Flux160s                              NaN
Flux480s             300295200000000000.0
Flux840s             599999800000000000.0
input_Energy                    32437.886
Temp_implantation                 104.475
Furance_Temp                          NaN
RTA_Temp                              157
Lot_Num                                27
Wafer_Num                              28
Datetime                       23-02-2019
Name: 1107, dtype: object

## 90 결측치 평균으로 채움

In [170]:
df['Flux90s'].agg('mean')

7.963297840520454e+16

In [171]:
df['Flux90s'].fillna(df['Flux90s'].agg('mean'), inplace = True)

In [143]:
df.loc[1107]

Unnamed: 0                           1107
No_Die                     NOLSM703271703
Chamber_Num                             1
process4                     Implantation
Flux60s               11802845338036440.0
Flux90s               79632978405204544.0
Flux160s                              NaN
Flux480s             300295200000000000.0
Flux840s             599999800000000000.0
input_Energy                    32437.886
Temp_implantation                 104.475
Furance_Temp                          NaN
RTA_Temp                              157
Lot_Num                                27
Wafer_Num                              28
Datetime                       23-02-2019
Name: 1107, dtype: object

## 90 음수값  양수로 바꾸기

In [160]:
df.loc[(df['Flux90s']<0)]

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
12,12,NOLSM3371313337,1,Implantation,1.128804e+16,-1.314100e+16,5.401109e+17,3.000265e+17,5.999993e+17,31201.477,103.231,902.0,158,13,40,01-03-2019
39,39,NOLSM3371313,1,Implantation,1.128804e+16,-1.314100e+16,5.401109e+17,3.000265e+17,5.999993e+17,31201.477,103.231,902.0,158,13,13,01-03-2019
54,54,NOLSM352141352,1,Implantation,1.091276e+16,-4.117940e+16,9.735337e+17,3.030090e+17,5.999988e+17,31292.665,100.718,899.0,151,14,28,02-03-2019
81,81,NOLSM352141,3,Implantation,1.091276e+16,-4.117940e+16,9.735337e+17,3.030090e+17,5.999988e+17,31292.665,100.718,899.0,151,14,1,02-03-2019
108,108,NOLSM379151379,1,Implantation,2.880388e+15,-1.195620e+16,5.215246e+17,3.006671e+17,5.999992e+17,32241.562,102.059,912.0,156,15,28,03-03-2019
135,135,NOLSM379151,3,Implantation,2.880388e+15,-1.195620e+16,5.215246e+17,3.006671e+17,5.999992e+17,32241.562,102.059,912.0,156,15,1,03-03-2019
767,767,NOLSM9341293,3,Implantation,1.692967e+16,-2.375230e+16,9.235683e+17,3.020301e+17,5.999990e+17,32179.174,103.426,890.0,158,4,39,20-02-2019
821,821,NOLSM93412,3,Implantation,1.692967e+16,-2.375230e+16,9.235683e+17,3.020301e+17,5.999990e+17,32179.174,103.426,890.0,158,4,12,20-02-2019
1199,1199,NOLSM201812201,3,Implantation,1.324488e+16,-5.324830e+15,1.044463e+18,3.004193e+17,5.999997e+17,32157.206,100.959,919.0,149,8,39,24-02-2019
1253,1253,NOLSM201812,3,Implantation,1.324488e+16,-5.324830e+15,1.044463e+18,3.004193e+17,5.999997e+17,32157.206,100.959,919.0,149,8,12,24-02-2019
1301,1301,NOLSM22296222,3,Implantation,1.865634e+16,-3.007830e+16,8.679111e+17,3.014537e+17,5.999998e+17,32497.987,102.546,919.0,156,9,33,25-02-2019
1355,1355,NOLSM22296,3,Implantation,1.865634e+16,-3.007830e+16,8.679111e+17,3.014537e+17,5.999998e+17,32497.987,102.546,919.0,156,9,6,25-02-2019
1519,1519,NOLSM278118278,2,Implantation,1.349019e+16,-1.677760e+16,8.485189e+17,2.995078e+17,6.000001e+17,32930.382,104.111,894.0,153,11,35,27-02-2019
1538,1538,NOLSM2971127297,3,Implantation,1.834814e+16,-2.769260e+16,1.050701e+18,3.003007e+17,6.000000e+17,31408.661,103.015,902.0,156,11,54,27-02-2019
1573,1573,NOLSM278118,3,Implantation,1.349019e+16,-1.677760e+16,8.485189e+17,2.995078e+17,6.000001e+17,32930.382,104.111,894.0,153,11,8,27-02-2019
1592,1592,NOLSM2971127,1,Implantation,1.834814e+16,-2.769260e+16,1.050701e+18,3.003007e+17,6.000000e+17,31408.661,103.015,902.0,156,11,27,27-02-2019

In [172]:
df.loc[(df['Flux90s']<0 ),'Flux90s'] = abs(df.loc[(df['Flux90s']<0 ),'Flux90s'])

In [68]:
df.loc[12]

Unnamed: 0                             12
No_Die                    NOLSM3371313337
Chamber_Num                             1
process4                     Implantation
Flux60s               11288040000000000.0
Flux90s               13141000000000000.0
Flux160s             540110900000000000.0
Flux480s             300026500000000000.0
Flux840s             599999300000000000.0
input_Energy                    31201.477
Temp_implantation                 103.231
Furance_Temp                        902.0
RTA_Temp                              158
Lot_Num                                13
Wafer_Num                              40
Datetime                       01-03-2019
Name: 12, dtype: object

## 160 음수값 양수로 바꾸기

In [161]:
df.loc[(df['Flux160s']<0)]

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
8,8,NOLSM333139333,3,Implantation,1.451580e+16,6.475248e+16,-8.789590e+15,3.013753e+17,6.000017e+17,31810.414,103.625,903.0,153,13,36,01-03-2019
35,35,NOLSM333139,2,Implantation,1.451580e+16,6.475248e+16,-8.789590e+15,3.013753e+17,6.000017e+17,31810.414,103.625,903.0,153,13,9,01-03-2019
130,130,NOLSM4011523401,2,Implantation,1.734001e+16,9.952238e+16,-6.118000e+16,3.002450e+17,5.999995e+17,32374.895,104.180,898.0,155,15,50,03-03-2019
157,157,NOLSM4011523,2,Implantation,1.734001e+16,9.952238e+16,-6.118000e+16,3.002450e+17,5.999995e+17,32374.895,104.180,898.0,155,15,23,03-03-2019
551,551,NOLSM3921239,3,Implantation,1.132399e+16,1.133253e+17,-6.930960e+16,2.994310e+17,6.000005e+17,31104.203,102.618,923.0,157,2,39,18-02-2019
605,605,NOLSM39212,3,Implantation,1.132399e+16,1.133253e+17,-6.930960e+16,2.994310e+17,6.000005e+17,31104.203,102.618,923.0,157,2,12,18-02-2019
1428,1428,NOLSM2681025268,1,Implantation,2.120762e+15,4.489405e+16,-6.597110e+16,2.990932e+17,5.999983e+17,30765.724,103.031,907.0,153,10,52,26-02-2019
1482,1482,NOLSM2681025,1,Implantation,2.120762e+15,4.489405e+16,-6.597110e+16,2.990932e+17,5.999983e+17,30765.724,103.031,907.0,153,10,25,26-02-2019

In [173]:
df.loc[(df['Flux160s']<0 ),'Flux160s'] = abs(df.loc[(df['Flux160s']<0 ),'Flux160s'])

In [71]:
df.loc[8]

Unnamed: 0                              8
No_Die                     NOLSM333139333
Chamber_Num                             3
process4                     Implantation
Flux60s               14515800000000000.0
Flux90s               64752480000000000.0
Flux160s               8789590000000000.0
Flux480s             301375300000000000.0
Flux840s             600001700000000000.0
input_Energy                    31810.414
Temp_implantation                 103.625
Furance_Temp                        903.0
RTA_Temp                              153
Lot_Num                                13
Wafer_Num                              36
Datetime                       01-03-2019
Name: 8, dtype: object

## 840 결측치 평균으로 채우기

In [174]:
df['Flux840s'].fillna(df['Flux840s'].agg('mean'), inplace = True)

# 480 결측치 평균으로 채우기

In [175]:
df['Flux480s'].fillna(df['Flux480s'].agg('mean'), inplace = True)

## 160 결측치 평균으로 채우기

In [176]:
df['Flux160s'].fillna(df['Flux160s'].agg('mean'), inplace = True)

In [177]:
df.to_csv('C:/Users/USER/Desktop/반도체 공정/데이터/음수값바꾸기.CSV')

## 160 480의 최소값으로채우기

In [166]:
df.loc[(df['Flux160s']>df['Flux480s']),'Flux160s']

0       6.468338e+17
1       1.041399e+18
2       6.473188e+17
3       3.408444e+17
4       7.255226e+17
            ...
1696    3.695368e+17
1697    1.026166e+18
1699    6.272553e+17
1701    3.069885e+17
1703    7.045878e+17
Name: Flux160s, Length: 1086, dtype: float64

In [150]:
 df['Flux480s'].min()

2.963401e+17

In [167]:
df.loc[(df['Flux160s']>df['Flux480s']),'Flux160s'] = df['Flux480s'].min()

In [152]:
df.loc[0]

Unnamed: 0                              8
No_Die                     NOLSM333139333
Chamber_Num                             3
process4                     Implantation
Flux60s               14515800000000000.0
Flux90s               64752480000000000.0
Flux160s               8789590000000000.0
Flux480s             301375300000000000.0
Flux840s             600001700000000000.0
input_Energy                    31810.414
Temp_implantation                 103.625
Furance_Temp                        903.0
RTA_Temp                              153
Lot_Num                                13
Wafer_Num                              36
Datetime                       01-03-2019
Name: 8, dtype: object

In [153]:
df.to_csv('C:/Users/USER/Desktop/반도체 공정/데이터/Ion_160 480최소값으로 변경.CSV')

In [ ]:
df.loc[(df['Flux160s']<df['Flux160s'].agg('mean')),'Flux160s'] = df['Flux480s'].min()

In [156]:
df.loc[(df['Flux160s']<df['Flux160s'].median()),'Flux160s']

8       8.789590e+15
11      2.201666e+17
18      1.994348e+17
21      2.168581e+17
35      8.789590e+15
            ...
1693    4.187844e+16
1695    2.115131e+14
1698    1.359659e+17
1700    1.865029e+17
1702    3.275209e+14
Name: Flux160s, Length: 614, dtype: float64

# 90이상치 160 의 최소값으로 변경

### 모두 160보다 작기 떄문에 90의 최솟값으로 변경

In [132]:
 df['Flux90s'].min()

3846247470.0

In [134]:
df.loc[(df['Flux90s']<32645606690),'Flux90s']

790     1.743402e+10
844     1.743402e+10
1326    3.264561e+10
1380    3.264561e+10
1431    3.846247e+09
1485    3.846247e+09
Name: Flux90s, dtype: float64

In [ ]:
df.loc[(df['Flux90s']<32645606690),'Flux90s'] = df['Flux90s'].min()

In [131]:
df.loc[(df['Flux90s']<df['Flux160s']),'Flux90s']

0       1.316363e+17
1       4.367509e+16
2       1.507393e+16
3       1.022922e+17
4       7.883038e+16
            ...
1699    9.513525e+16
1700    5.426149e+16
1701    7.673877e+15
1702    2.793792e+16
1703    1.496121e+17
Name: Flux90s, Length: 1704, dtype: float64

In [116]:
df.loc[(df['Flux90s']<df['Flux160s']),'Flux90s'] = df['Flux160s'].min()

In [117]:
df.loc[0:4]

,Unnamed: 0,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
0,0,NOLSM325131325,1,Implantation,1.500198e+16,2.963401e+17,6.468338e+17,3.011187e+17,6.000012e+17,30795.934,103.433,854.0,154,13,28,01-03-2019
1,1,NOLSM326132326,2,Implantation,1.105654e+16,2.963401e+17,1.041399e+18,3.026639e+17,6.000008e+17,32135.618,105.552,895.0,156,13,29,01-03-2019
2,2,NOLSM327133327,3,Implantation,1.044283e+16,2.963401e+17,6.473188e+17,2.983347e+17,5.999989e+17,31057.895,102.598,898.0,152,13,30,01-03-2019
3,3,NOLSM328134328,1,Implantation,8.885135e+15,2.963401e+17,3.408444e+17,2.999225e+17,5.999997e+17,32140.566,102.963,879.0,155,13,31,01-03-2019
4,4,NOLSM329135329,2,Implantation,1.665762e+16,2.963401e+17,7.255226e+17,3.018136e+17,6.000004e+17,31986.009,101.419,882.0,155,13,32,01-03-2019

In [119]:
df.loc[(df['Flux60s']<df['Flux90s']),'Flux60s']

0       1.500198e+16
1       1.105654e+16
2       1.044283e+16
3       8.885135e+15
4       1.665762e+16
            ...
1699    1.054583e+16
1700    6.909171e+15
1701    9.324972e+15
1702    1.184106e+16
1703    1.511777e+16
Name: Flux60s, Length: 1704, dtype: float64

In [118]:
df.to_csv('C:/Users/USER/Desktop/반도체 공정/데이터/Ion_90 160최소값으로 변경.CSV')

In [76]:
df.isnull().sum()

Unnamed: 0           0
No_Die               0
Chamber_Num          0
process4             0
Flux60s              0
Flux90s              0
Flux160s             0
Flux480s             0
Flux840s             0
input_Energy         0
Temp_implantation    0
Furance_Temp         2
RTA_Temp             0
Lot_Num              0
Wafer_Num            0
Datetime             0
dtype: int64

In [136]:
df = pd.read_csv("C:/Users/USER/Desktop/반도체 공정/데이터/Ion_160 480최소값으로 변경.CSV")
df

,Unnamed: 0,Unnamed: 0.1,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
0,0,0,NOLSM325131325,1,Implantation,1.500198e+16,1.316363e+17,6.468338e+17,3.011187e+17,6.000012e+17,30795.934,103.433,854.0,154,13,28,01-03-2019
1,1,1,NOLSM326132326,2,Implantation,1.105654e+16,4.367509e+16,1.041399e+18,3.026639e+17,6.000008e+17,32135.618,105.552,895.0,156,13,29,01-03-2019
2,2,2,NOLSM327133327,3,Implantation,1.044283e+16,1.507393e+16,6.473188e+17,2.983347e+17,5.999989e+17,31057.895,102.598,898.0,152,13,30,01-03-2019
3,3,3,NOLSM328134328,1,Implantation,8.885135e+15,1.022922e+17,3.408444e+17,2.999225e+17,5.999997e+17,32140.566,102.963,879.0,155,13,31,01-03-2019
4,4,4,NOLSM329135329,2,Implantation,1.665762e+16,7.883038e+16,7.255226e+17,3.018136e+17,6.000004e+17,31986.009,101.419,882.0,155,13,32,01-03-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,1699,1699,NOLSM8483211,3,Implantation,1.054583e+16,9.513525e+16,6.272553e+17,3.009325e+17,6.000003e+17,32248.621,101.503,868.0,152,32,11,28-02-2019
1700,1700,1700,NOLSM8493212,3,Implantation,6.909171e+15,5.426149e+16,2.963401e+17,3.006733e+17,6.000003e+17,32241.426,101.061,867.0,152,32,12,28-02-2019
1701,1701,1701,NOLSM8503213,2,Implantation,9.324972e+15,7.673877e+15,3.069885e+17,2.990013e+17,5.999991e+17,32245.574,101.506,868.0,152,32,13,28-02-2019
1702,1702,1702,NOLSM8513214,1,Implantation,1.184106e+16,2.793792e+16,2.963401e+17,2.992776e+17,6.000012e+17,32259.412,101.360,868.0,152,32,14,28-02-2019
1703,1703,1703,NOLSM8523215,1,Implantation,1.511777e+16,1.496121e+17,7.045878e+17,2.990793e+17,6.000008e+17,32258.401,101.439,868.0,152,32,15,28-02-2019

In [138]:
df.loc[(df['Flux160s']>df['Flux480s']),'Flux160s']

0       6.468338e+17
1       1.041399e+18
2       6.473188e+17
3       3.408444e+17
4       7.255226e+17
            ...
1696    3.695368e+17
1697    1.026166e+18
1699    6.272553e+17
1701    3.069885e+17
1703    7.045878e+17
Name: Flux160s, Length: 1086, dtype: float64

In [178]:
df = pd.read_csv("C:/Users/USER/Desktop/반도체 공정/데이터/음수값바꾸기.CSV")
df

,Unnamed: 0,Unnamed: 0.1,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
0,0,0,NOLSM325131325,1,Implantation,1.500198e+16,1.316363e+17,6.468338e+17,3.011187e+17,6.000012e+17,30795.934,103.433,854.0,154,13,28,01-03-2019
1,1,1,NOLSM326132326,2,Implantation,1.105654e+16,4.367509e+16,1.041399e+18,3.026639e+17,6.000008e+17,32135.618,105.552,895.0,156,13,29,01-03-2019
2,2,2,NOLSM327133327,3,Implantation,1.044283e+16,1.507393e+16,6.473188e+17,2.983347e+17,5.999989e+17,31057.895,102.598,898.0,152,13,30,01-03-2019
3,3,3,NOLSM328134328,1,Implantation,8.885135e+15,1.022922e+17,3.408444e+17,2.999225e+17,5.999997e+17,32140.566,102.963,879.0,155,13,31,01-03-2019
4,4,4,NOLSM329135329,2,Implantation,1.665762e+16,7.883038e+16,7.255226e+17,3.018136e+17,6.000004e+17,31986.009,101.419,882.0,155,13,32,01-03-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,1699,1699,NOLSM8483211,3,Implantation,1.054583e+16,9.513525e+16,6.272553e+17,3.009325e+17,6.000003e+17,32248.621,101.503,868.0,152,32,11,28-02-2019
1700,1700,1700,NOLSM8493212,3,Implantation,6.909171e+15,5.426149e+16,1.865029e+17,3.006733e+17,6.000003e+17,32241.426,101.061,867.0,152,32,12,28-02-2019
1701,1701,1701,NOLSM8503213,2,Implantation,9.324972e+15,7.673877e+15,3.069885e+17,2.990013e+17,5.999991e+17,32245.574,101.506,868.0,152,32,13,28-02-2019
1702,1702,1702,NOLSM8513214,1,Implantation,1.184106e+16,2.793792e+16,3.275209e+14,2.992776e+17,6.000012e+17,32259.412,101.360,868.0,152,32,14,28-02-2019
1703,1703,1703,NOLSM8523215,1,Implantation,1.511777e+16,1.496121e+17,7.045878e+17,2.990793e+17,6.000008e+17,32258.401,101.439,868.0,152,32,15,28-02-2019

In [179]:
df.loc[(df['Flux160s']>df['Flux480s']),'Flux160s']

0       6.468338e+17
1       1.041399e+18
2       6.473188e+17
3       3.408444e+17
4       7.255226e+17
            ...
1696    3.695368e+17
1697    1.026166e+18
1699    6.272553e+17
1701    3.069885e+17
1703    7.045878e+17
Name: Flux160s, Length: 1086, dtype: float64

In [180]:
df.loc[(df['Flux160s']>df['Flux480s']),'Flux160s'] = df['Flux480s'].min()

In [181]:
df.loc[0]

Unnamed: 0                              0
Unnamed: 0.1                            0
No_Die                     NOLSM325131325
Chamber_Num                             1
process4                     Implantation
Flux60s               15001980000000000.0
Flux90s              131636300000000000.0
Flux160s             296340100000000000.0
Flux480s             301118700000000000.0
Flux840s             600001200000000000.0
input_Energy                    30795.934
Temp_implantation                 103.433
Furance_Temp                        854.0
RTA_Temp                              154
Lot_Num                                13
Wafer_Num                              28
Datetime                       01-03-2019
Name: 0, dtype: object

In [184]:
df = pd.read_csv("C:/Users/USER/Desktop/반도체 공정/데이터/160 480보다 큰거 480 최소로 처리.CSV")

In [186]:
df.loc[(df['Flux160s']<df['Flux160s'].agg('mean')),'Flux160s'] =df['Flux160s'].agg('mean')

In [187]:
df.to_csv('C:/Users/USER/Desktop/반도체 공정/데이터/Ion160 이상치 평균으로변경.CSV')

In [189]:
df = pd.read_csv("C:/Users/USER/Desktop/반도체 공정/데이터/Ion160 이상치 평균으로변경.CSV")
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,No_Die,Chamber_Num,process4,Flux60s,Flux90s,Flux160s,Flux480s,Flux840s,input_Energy,Temp_implantation,Furance_Temp,RTA_Temp,Lot_Num,Wafer_Num,Datetime
0,0,0,0,0,NOLSM325131325,1,Implantation,1.500198e+16,1.316363e+17,2.963401e+17,3.011187e+17,6.000012e+17,30795.934,103.433,854.0,154,13,28,01-03-2019
1,1,1,1,1,NOLSM326132326,2,Implantation,1.105654e+16,4.367509e+16,2.963401e+17,3.026639e+17,6.000008e+17,32135.618,105.552,895.0,156,13,29,01-03-2019
2,2,2,2,2,NOLSM327133327,3,Implantation,1.044283e+16,1.507393e+16,2.963401e+17,2.983347e+17,5.999989e+17,31057.895,102.598,898.0,152,13,30,01-03-2019
3,3,3,3,3,NOLSM328134328,1,Implantation,8.885135e+15,1.022922e+17,2.963401e+17,2.999225e+17,5.999997e+17,32140.566,102.963,879.0,155,13,31,01-03-2019
4,4,4,4,4,NOLSM329135329,2,Implantation,1.665762e+16,7.883038e+16,2.963401e+17,3.018136e+17,6.000004e+17,31986.009,101.419,882.0,155,13,32,01-03-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,1699,1699,1699,1699,NOLSM8483211,3,Implantation,1.054583e+16,9.513525e+16,2.963401e+17,3.009325e+17,6.000003e+17,32248.621,101.503,868.0,152,32,11,28-02-2019
1700,1700,1700,1700,1700,NOLSM8493212,3,Implantation,6.909171e+15,5.426149e+16,2.210559e+17,3.006733e+17,6.000003e+17,32241.426,101.061,867.0,152,32,12,28-02-2019
1701,1701,1701,1701,1701,NOLSM8503213,2,Implantation,9.324972e+15,7.673877e+15,2.963401e+17,2.990013e+17,5.999991e+17,32245.574,101.506,868.0,152,32,13,28-02-2019
1702,1702,1702,1702,1702,NOLSM8513214,1,Implantation,1.184106e+16,2.793792e+16,2.210559e+17,2.992776e+17,6.000012e+17,32259.412,101.360,868.0,152,32,14,28-02-2019
1703,1703,1703,1703,1703,NOLSM8523215,1,Implantation,1.511777e+16,1.496121e+17,2.963401e+17,2.990793e+17,6.000008e+17,32258.401,101.439,868.0,152,32,15,28-02-2019

In [206]:
df.loc[(df['Flux60s']>df['Flux90s']),'Flux60s']

25      1.882341e+16
52      1.882341e+16
77      6.412499e+15
104     6.412499e+15
270     1.708263e+16
            ...
1650    1.609899e+16
1659    9.324972e+15
1691    4.590594e+15
1692    1.609899e+16
1701    9.324972e+15
Name: Flux60s, Length: 237, dtype: float64